# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'rb-frontend/package-lock.json'

    - run: npm ci
      working-directory: 'rb-frontend'
    - run: npm install
      working-directory: 'rb-frontend'
    - run: npm run build
      working-directory: 'rb-frontend'
    - run: npm test
      working-directory: 'rb-frontend'
    - run: npm run lint
      working-directory: 'rb-frontend'
      env:
        CI: true
